name: ColorGameForLinux # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: ColorGameForLinux Snapd # 79 char long summary
description: | You need to pick what color the text is but be warned the text will say a different color and may trick you! Do you have what it takes to get 100 points in 90 seconds? 
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
